Disabling lockstep simulation for AirSim and adding optional parameter arguments for SITL

diff --git a/ROMFS/px4fmu_common/init.d-posix/rcS b/ROMFS/px4fmu_common/init.d-posix/rcS
--- a/ROMFS/px4fmu_common/init.d-posix/rcS
+++ b/ROMFS/px4fmu_common/init.d-posix/rcS
@@ -7,6 +7,15 @@
 
 SCRIPT_DIR="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)"
 
+PX4_ESTIMATOR="ekf2"
+PX4_DISABLE_FAILSAFE=1
+PX4_USE_EXTERNAL_POSE=0
+PX4_USE_TCP=1
+
+MAVSDK_SERVER_IP="$(host mavsdk-server | grep -oE '\b([0-9]{1,3}\.){3}[0-9]{1,3}\b')"
+echo "MAVSDK_SERVER_IP XXX: $MAVSDK_SERVER_IP"
+echo "PX4_SIM_MODEL: $PX4_SIM_MODEL"
+echo "PX4_ESTIMATOR: $PX4_ESTIMATOR"
 #
 # Main SITL startup script
 #
@@ -107,13 +116,21 @@ fi
 # multi-instance setup
 # shellcheck disable=SC2154
 param set MAV_SYS_ID $((px4_instance+1))
+param set MAV_BROADCAST 1
 simulator_tcp_port=$((4560+px4_instance))
+simulator_udp_port=$((14560+px4_instance))
 udp_offboard_port_local=$((14580+px4_instance))
 udp_offboard_port_remote=$((14540+px4_instance))
 [ $px4_instance -gt 9 ] && udp_offboard_port_remote=14549 # use the same ports for more than 10 instances to avoid port overlaps
 udp_onboard_payload_port_local=$((14280+px4_instance))
 udp_onboard_payload_port_remote=$((14030+px4_instance))
 udp_gcs_port_local=$((18570+px4_instance))
+
+if [ "$PX4_USE_TCP" = 1 ]; then
+	echo "Simulator TCP Port: $simulator_tcp_port"
+else
+	echo "Simulator UDP Port: $simulator_udp_port"
+fi
 
 if [ $AUTOCNF = yes ]
 then
@@ -175,6 +192,24 @@ then
 	param set TRIG_INTERFACE 3
 fi
 
+# Use environment variable PX4_USE_EXTERNAL_POSE to set external odometry
+if [ "$PX4_USE_EXTERNAL_POSE" = 1 ]; then
+	echo "Using external position source, set EKF2_AID_MASK 8"
+	param set EKF2_AID_MASK 8
+else
+	param set EKF2_AID_MASK 1
+	echo "Not using External Position"
+fi
+
+if [ "$PX4_DISABLE_FAILSAFE" = 1 ]; then
+	echo "Disable Failsafe check"
+	param set NAV_DLL_ACT 0
+	param set NAV_RCL_ACT 0
+	param set NAV_TRAFF_AVOID 0
+else
+	echo "Not disabling failsafe check"
+fi
+
 param set COM_CPU_MAX -1 # disable check, no CPU load reported on posix yet
 
 # Simulator IMU data provided at 250 Hz
@@ -226,10 +261,21 @@ fi
 
 dataman start
 # only start the simulator if not in replay mode, as both control the lockstep time
+# if ! replay tryapplyparams
+# then
+# 	simulator start -c $simulator_tcp_port
+# fi
 if ! replay tryapplyparams
 then
-	simulator start -c $simulator_tcp_port
+	if [ "$PX4_USE_TCP" = 1 ]; then
+		echo "Using TCP connection to ${simulator_tcp_port}"
+		simulator start -c $simulator_tcp_port
+	else
+		echo "Using UDP connection to ${simulator_udp_port}"
+		simulator start -s -u $simulator_udp_port
+	fi
 fi
+
 battery_simulator start
 tone_alarm start
 rc_update start
@@ -268,7 +314,14 @@ mavlink stream -r 20 -s RC_CHANNELS -u $udp_gcs_port_local
 mavlink stream -r 10 -s OPTICAL_FLOW_RAD -u $udp_gcs_port_local
 
 # API/Offboard link
-mavlink start -x -u $udp_offboard_port_local -r 4000000 -m onboard -o $udp_offboard_port_remote
+if [ -z "$MAVSDK_SERVER_IP" ]
+then
+	echo "MAVSDK_SERVER_IP Empty: $MAVSDK_SERVER_IP"
+	mavlink start -x -u $udp_offboard_port_local -r 4000000 -m onboard -o $udp_offboard_port_remote
+else
+	echo "MAVSDK_SERVER_IP XXX: $MAVSDK_SERVER_IP"
+	mavlink start -x -u $udp_offboard_port_local -r 4000000 -m onboard -t $MAVSDK_SERVER_IP -o $udp_offboard_port_remote
+fi
 
 # Onboard link to camera
 mavlink start -x -u $udp_onboard_payload_port_local -r 4000 -f -m onboard -o $udp_onboard_payload_port_remote
